name: first_workflow

on: 
  push:
    branches:
      - main
jobs:
   hello:
    runs-on: ubuntu-latest
    steps:
      - name: vanakkam
        run: echo "vanakkam Nalin"
        shell: bash
 
   kissmiss:
     runs-on: ubuntu-latest
     steps:
      - name: Thamizh
        run: echo "Vazharga"
        shell: bash
       
     
