name: first_workflow

on: 
  push:
    branches:
      - main
     
     
jobs:
   hello:
    runs-on: ubuntu_latest
    steps:
      - name: vanakkam
        run: echo "vanakkam Nalin"
        shell: bash
