name: first_workflow

on: 
  push:
    branches:
      - main
workflow_dispatch:

jobs:
   hello:
    runs-on: ubuntu-latest
    steps:
      - name: vanakkam
        run: echo "vanakkam Nalin"
        shell: bash
